# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

api_usage <- function() {
    .Call(`_brkga_api_usage`)
}

tsp_brkga <- function(instanceFile) {
    .Call(`_brkga_tsp_brkga`, instanceFile)
}

rcpparma_hello_world <- function() {
    .Call(`_brkga_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_brkga_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_brkga_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_brkga_rcpparma_bothproducts`, x)
}

