# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get fitness from tour
#' @details Get fitness using the tour, m and distance matrix
#' @param \code{Tour} Set of tour's nodes.
#' @param \code{Distances} Distance matrix
#' @return A double value representing the chromosome fitness
#' @export 
getTourFitness <- function(Tour, Distances) {
    .Call(`_brkga_getTourFitness`, Tour, Distances)
}

#' Get fitness from chromosome
#' @details Get fitness using chromossome, m and distance matrix
#' @param \code{chromosome} Chromosome
#' @param \code{Distances} Distance matrix
#' @param \code{m} Size of tour
#' @return A double value representing the chromosome fitness
#' @export 
getChromosomeFitness <- function(chromosome, Distances, m) {
    .Call(`_brkga_getChromosomeFitness`, chromosome, Distances, m)
}

#' Execute a MDP solution search using BRKGA
#' @details Escrever um detalhamento bem legal e super bacana
#'  aqui.
#' @param \code{DistanceMatrix} distances matrix of the instance 
#' @param \code{m} Number of elements selected (m <= n)
#' @param \code{LS_INTVL} Generations between local searches
#' @param \code{GEN_INTVL} Generations in each evolution;
#' @param \code{MAX_TIME}  Max time of execution in seconds
#' @param \code{p}  Size of population
#' @param \code{pe} Fraction of population to be the elite-set
#' @param \code{pm} Fraction of population to be replaced by mutants
#' @param \code{rhoe} Frobability that offspring inherit an allele from elite parent
#' @param \code{lambda} probability update population with local search
#' @param \code{K} number of independent populations
#' @param \code{THREADS} number of threads for parallel decoding
#' @param \code{X_INTVL} Exchange best individuals at every 100 generations
#' @param \code{X_NUMBER} Exchange top 2 best
#' @param \code{MAX_GENS} Max number of generations
#' @param \code{verbose} Level of output information
#' @param \code{rngSeed} Seed to the random number generator
#' @return A numeric vector of random values
#' @seealso \code{\link{api-usage}} and \url{https://github.com/milkway/brkga}
#' @export 
mdp_brkga <- function(DistanceMatrix, m, method = 0L, LS_INTVL = 5L, GEN_INTVL = 5L, MAX_TIME = 10L, p = 500L, pe = 0.20, pm = 0.10, rhoe = 0.70, lambda = 0.01, K = 3L, THREADS = 8L, X_INTVL = 100L, X_NUMBER = 2L, MAX_GENS = 100L, RESET_AFTER = 200L, verbose = FALSE, rngSeed = 0L) {
    .Call(`_brkga_mdp_brkga`, DistanceMatrix, m, method, LS_INTVL, GEN_INTVL, MAX_TIME, p, pe, pm, rhoe, lambda, K, THREADS, X_INTVL, X_NUMBER, MAX_GENS, RESET_AFTER, verbose, rngSeed)
}

#' Execute a MDP solution search using BRKGA
#' @details Escrever um detalhamento bem legal e super bacana
#'  aqui.
#' @param \code{DistanceMatrix} distances matrix of the instance 
#' @param \code{m} Number of elements selected (m <= n)
#' @param \code{MAX_TIME}  Max time of execution in seconds
#' @param \code{p}  Size of population
#' @param \code{pe} Fraction of population to be the elite-set
#' @param \code{pm} Fraction of population to be replaced by mutants
#' @param \code{rhoe} Frobability that offspring inherit an allele from elite parent
#' @param \code{lambda} probability update population with local search
#' @param \code{K} number of independent populations
#' @param \code{THREADS} number of threads for parallel decoding
#' @param \code{X_INTVL} Exchange best individuals at every 100 generations
#' @param \code{X_NUMBER} Exchange top 2 best
#' @param \code{MAX_GENS} Max number of generations
#' @param \code{verbose} Level of output information
#' @param \code{rngSeed} Seed to the random number generator
#' @return A numeric vector of random values
#' @seealso \code{\link{api-usage}} and \url{https://github.com/milkway/brkga}
#' @export 
mdp_brkgals <- function(DistanceMatrix, m, method = 0L, LS_INTVL = 10L, GEN_INTVL = 5L, MAX_TIME = 10L, p = 500L, pe = 0.20, pm = 0.10, rhoe = 0.70, lambda = 0.01, K = 3L, THREADS = 8L, X_INTVL = 100L, X_NUMBER = 2L, MAX_GENS = 100L, RESET_AFTER = 200L, verbose = TRUE, rngSeed = 0L) {
    .Call(`_brkga_mdp_brkgals`, DistanceMatrix, m, method, LS_INTVL, GEN_INTVL, MAX_TIME, p, pe, pm, rhoe, lambda, K, THREADS, X_INTVL, X_NUMBER, MAX_GENS, RESET_AFTER, verbose, rngSeed)
}

#' Execute a MDP solution search using BRKGA
#' @details Escrever um detalhamento bem legal e super bacana
#'  aqui.
#' @param \code{DistanceMatrix} distances matrix of the instance 
#' @param \code{m} Number of elements selected (m <= n)
#' @param \code{MAX_TIME}  Max time of execution in seconds
#' @param \code{p}  Size of population
#' @param \code{pe} Fraction of population to be the elite-set
#' @param \code{pm} Fraction of population to be replaced by mutants
#' @param \code{rhoe} Frobability that offspring inherit an allele from elite parent
#' @param \code{lambda} probability update population with local search
#' @param \code{K} number of independent populations
#' @param \code{THREADS} number of threads for parallel decoding
#' @param \code{X_INTVL} Exchange best individuals at every 100 generations
#' @param \code{X_NUMBER} Exchange top 2 best
#' @param \code{MAX_GENS} Max number of generations
#' @param \code{verbose} Level of output information
#' @param \code{rngSeed} Seed to the random number generator
#' @return A numeric vector of random values
#' @seealso \code{\link{api-usage}} and \url{https://github.com/milkway/brkga}
#' @export 
mdp_brkgaus <- function(DistanceMatrix, m, method = 0L, LS_INTVL = 10L, GEN_INTVL = 5L, MAX_TIME = 10L, p = 500L, pe = 0.20, pm = 0.10, rhoe = 0.70, lambda = 0.01, K = 3L, THREADS = 8L, X_INTVL = 100L, X_NUMBER = 2L, MAX_GENS = 100L, RESET_AFTER = 200L, verbose = TRUE, rngSeed = 0L) {
    .Call(`_brkga_mdp_brkgaus`, DistanceMatrix, m, method, LS_INTVL, GEN_INTVL, MAX_TIME, p, pe, pm, rhoe, lambda, K, THREADS, X_INTVL, X_NUMBER, MAX_GENS, RESET_AFTER, verbose, rngSeed)
}

#' Execute a MDP solution search using BRKGA
#' @details Escrever um detalhamento bem legal e super bacana
#'  aqui.
#' @param MAX_TIME  Max time of execution in seconds
#' @param p  Size of population
#' @param pe Fraction of population to be the elite-set
#' @param pm Fraction of population to be replaced by mutants
#' @param rhoe Frobability that offspring inherit an allele from elite parent
#' @param K number of independent populations
#' @param MAXT number of threads for parallel decoding
#' @param X_INTVL Exchange best individuals at every 100 generations
#' @param X_NUMBER Exchange top 2 best
#' @param MAX_GENS Max number of generations
#' @param SEM_MELHORA  Pergunte para Geiza
#' @param verbose Level of output information
#' @param rngSeed Seed to the random number generator
#' @return A numeric vector of random values
#' @seealso \code{\link{api-usage}} and \url{https://github.com/milkway/brkga}
#' @export 
nl_brkga <- function(func_, lowerLimit, upperLimit, p = 100L, pe = 0.10, pm = 0.10, rhoe = 0.70, K = 3L, MAXT = 1L, verbose = FALSE, rngSeed = 0L, X_INTVL = 100L, X_NUMBER = 2L, MAX_GENS = 1000L) {
    .Call(`_brkga_nl_brkga`, func_, lowerLimit, upperLimit, p, pe, pm, rhoe, K, MAXT, verbose, rngSeed, X_INTVL, X_NUMBER, MAX_GENS)
}

Ackleys <- function(X) {
    .Call(`_brkga_Ackleys`, X)
}

AluffiPentini <- function(X) {
    .Call(`_brkga_AluffiPentini`, X)
}

BeckerLago <- function(X) {
    .Call(`_brkga_BeckerLago`, X)
}

Bohachevsky1 <- function(X) {
    .Call(`_brkga_Bohachevsky1`, X)
}

Bohachevsky2 <- function(X) {
    .Call(`_brkga_Bohachevsky2`, X)
}

Branin <- function(X, a = 1., b = 5.1/(4*pi*pi), c = 5/pi, d = 6., e = 10., f = 1/(8*pi)) {
    .Call(`_brkga_Branin`, X, a, b, c, d, e, f)
}

Camel3 <- function(X) {
    .Call(`_brkga_Camel3`, X)
}

Camel6 <- function(X) {
    .Call(`_brkga_Camel6`, X)
}

CosMixN <- function(X) {
    .Call(`_brkga_CosMixN`, X)
}

DekkersAarts <- function(X) {
    .Call(`_brkga_DekkersAarts`, X)
}

Easom <- function(X) {
    .Call(`_brkga_Easom`, X)
}

EMichalewicz <- function(X, m = 10.) {
    .Call(`_brkga_EMichalewicz`, X, m)
}

Expo <- function(X) {
    .Call(`_brkga_Expo`, X)
}

GoldPrice <- function(X) {
    .Call(`_brkga_GoldPrice`, X)
}

Griewank <- function(X) {
    .Call(`_brkga_Griewank`, X)
}

Gulf <- function(X) {
    .Call(`_brkga_Gulf`, X)
}

Hartman3 <- function(X) {
    .Call(`_brkga_Hartman3`, X)
}

Hartman6 <- function(X) {
    .Call(`_brkga_Hartman6`, X)
}

Hosaki <- function(X) {
    .Call(`_brkga_Hosaki`, X)
}

Kowalik <- function(X) {
    .Call(`_brkga_Kowalik`, X)
}

LM1 <- function(X) {
    .Call(`_brkga_LM1`, X)
}

McCormic <- function(X) {
    .Call(`_brkga_McCormic`, X)
}

MeyerRoth <- function(X) {
    .Call(`_brkga_MeyerRoth`, X)
}

MieleCantrell <- function(X) {
    .Call(`_brkga_MieleCantrell`, X)
}

Modlangerman <- function(X) {
    .Call(`_brkga_Modlangerman`, X)
}

ModRosenbrock <- function(X) {
    .Call(`_brkga_ModRosenbrock`, X)
}

MultiGauss <- function(X) {
    .Call(`_brkga_MultiGauss`, X)
}

Neumaier2 <- function(X) {
    .Call(`_brkga_Neumaier2`, X)
}

Neumaier3 <- function(X) {
    .Call(`_brkga_Neumaier3`, X)
}

Paviani <- function(X) {
    .Call(`_brkga_Paviani`, X)
}

Periodic <- function(X) {
    .Call(`_brkga_Periodic`, X)
}

PowellQ <- function(X) {
    .Call(`_brkga_PowellQ`, X)
}

PriceTransistor <- function(X) {
    .Call(`_brkga_PriceTransistor`, X)
}

Rastrigin <- function(X) {
    .Call(`_brkga_Rastrigin`, X)
}

Rosenbrock <- function(X) {
    .Call(`_brkga_Rosenbrock`, X)
}

Salomon <- function(X) {
    .Call(`_brkga_Salomon`, X)
}

Schaffer1 <- function(X) {
    .Call(`_brkga_Schaffer1`, X)
}

Schaffer2 <- function(X) {
    .Call(`_brkga_Schaffer2`, X)
}

Schubert <- function(X) {
    .Call(`_brkga_Schubert`, X)
}

Schwefel <- function(X) {
    .Call(`_brkga_Schwefel`, X)
}

Shekel10 <- function(X) {
    .Call(`_brkga_Shekel10`, X)
}

Shekel5 <- function(X) {
    .Call(`_brkga_Shekel5`, X)
}

Shekel7 <- function(X) {
    .Call(`_brkga_Shekel7`, X)
}

Shekelfox5 <- function(X) {
    .Call(`_brkga_Shekelfox5`, X)
}

Wood <- function(X) {
    .Call(`_brkga_Wood`, X)
}

Zeldasine <- function(X, A = 2.5, B = 5.) {
    .Call(`_brkga_Zeldasine`, X, A, B)
}

reg_beta <- function(X, data) {
    .Call(`_brkga_reg_beta`, X, data)
}

#' Execute a MDP solution search using BRKGA
#' @details Escrever um detalhamento bem legal e super bacana
#'  aqui.
#' @param MAX_TIME  Max time of execution in seconds
#' @param p  Size of population
#' @param pe Fraction of population to be the elite-set
#' @param pm Fraction of population to be replaced by mutants
#' @param rhoe Frobability that offspring inherit an allele from elite parent
#' @param K number of independent populations
#' @param MAXT number of threads for parallel decoding
#' @param X_INTVL Exchange best individuals at every 100 generations
#' @param X_NUMBER Exchange top 2 best
#' @param MAX_GENS Max number of generations
#' @param SEM_MELHORA  Pergunte para Geiza
#' @param verbose Level of output information
#' @param rngSeed Seed to the random number generator
#' @return A numeric vector of random values
#' @seealso \code{\link{api-usage}} and \url{https://github.com/milkway/brkga}
#' @export 
reg_brkga <- function(func_, lowerLimit, upperLimit, p = 100L, pe = 0.10, pm = 0.10, rhoe = 0.70, K = 3L, MAXT = 1L, verbose = FALSE, data = NULL, rngSeed = 0L, X_INTVL = 100L, X_NUMBER = 2L, MAX_GENS = 1000L) {
    .Call(`_brkga_reg_brkga`, func_, lowerLimit, upperLimit, p, pe, pm, rhoe, K, MAXT, verbose, data, rngSeed, X_INTVL, X_NUMBER, MAX_GENS)
}

#' Execute a MDP solution search using BRKGA
#' @details Escrever um detalhamento bem legal e super bacana
#'  aqui.
#' @param MAX_TIME  Max time of execution in seconds
#' @param p  Size of population
#' @param pe Fraction of population to be the elite-set
#' @param pm Fraction of population to be replaced by mutants
#' @param rhoe Frobability that offspring inherit an allele from elite parent
#' @param K number of independent populations
#' @param MAXT number of threads for parallel decoding
#' @param X_INTVL Exchange best individuals at every 100 generations
#' @param X_NUMBER Exchange top 2 best
#' @param MAX_GENS Max number of generations
#' @param SEM_MELHORA  Pergunte para Geiza
#' @param verbose Level of output information
#' @param rngSeed Seed to the random number generator
#' @return A numeric vector of random values
#' @seealso \code{\link{api-usage}} and \url{https://github.com/milkway/brkga}
#' @export 
tsp_brkga <- function(instanceFile) {
    .Call(`_brkga_tsp_brkga`, instanceFile)
}

